// export { ReactComponent as ABS01 } from "./dualtone/abs001.svg";
// export { ReactComponent as ABS02 } from "./dualtone/abs002.svg";
// export { ReactComponent as ABS03 } from "./dualtone/abs003.svg";
// export { ReactComponent as ABS04 } from "./dualtone/abs004.svg";
// export { ReactComponent as ABS05 } from "./dualtone/abs005.svg";
// export { ReactComponent as ABS06 } from "./dualtone/abs006.svg";
// export { ReactComponent as ABS07 } from "./dualtone/abs007.svg";
// export { ReactComponent as ABS08 } from "./dualtone/abs008.svg";
// export { ReactComponent as ABS09 } from "./dualtone/abs009.svg";
// export { ReactComponent as ABS10 } from "./dualtone/abs010.svg";
// export { ReactComponent as ABS11 } from "./dualtone/abs011.svg";
// export { ReactComponent as ABS12 } from "./dualtone/abs012.svg";
export { ReactComponent as ABS13 } from "./dualtone/abs013.svg";
export { ReactComponent as ABS14 } from "./dualtone/abs014.svg";
// export { ReactComponent as ABS15 } from "./dualtone/abs015.svg";
// export { ReactComponent as ABS16 } from "./dualtone/abs016.svg";
// export { ReactComponent as ABS17 } from "./dualtone/abs017.svg";
// export { ReactComponent as ABS18 } from "./dualtone/abs018.svg";
// export { ReactComponent as ABS19 } from "./dualtone/abs019.svg";
export { ReactComponent as ABS20 } from "./dualtone/abs020.svg";
// export { ReactComponent as ABS21 } from "./dualtone/abs021.svg";
export { ReactComponent as ABS22 } from "./dualtone/abs022.svg";
export { ReactComponent as ABS23 } from "./dualtone/abs023.svg";
export { ReactComponent as ABS24 } from "./dualtone/abs024.svg";
export { ReactComponent as ABS25 } from "./dualtone/abs025.svg";
export { ReactComponent as ABS26 } from "./dualtone/abs026.svg";
export { ReactComponent as ABS27 } from "./dualtone/abs027.svg";
export { ReactComponent as ABS28 } from "./dualtone/abs028.svg";
// export { ReactComponent as ABS29 } from "./dualtone/abs029.svg";
// export { ReactComponent as ABS30 } from "./dualtone/abs030.svg";
// export { ReactComponent as ABS31 } from "./dualtone/abs031.svg";
export { ReactComponent as ABS32 } from "./dualtone/abs032.svg";
// export { ReactComponent as ABS33 } from "./dualtone/abs033.svg";
// export { ReactComponent as ABS34 } from "./dualtone/abs034.svg";
// export { ReactComponent as ABS35 } from "./dualtone/abs035.svg";
// export { ReactComponent as ABS36 } from "./dualtone/abs036.svg";
// export { ReactComponent as ABS37 } from "./dualtone/abs037.svg";
// export { ReactComponent as ABS38 } from "./dualtone/abs038.svg";
// export { ReactComponent as ABS39 } from "./dualtone/abs039.svg";
// export { ReactComponent as ABS40 } from "./dualtone/abs040.svg";
// export { ReactComponent as ABS41 } from "./dualtone/abs041.svg";
// export { ReactComponent as ABS42 } from "./dualtone/abs042.svg";
// export { ReactComponent as ABS43 } from "./dualtone/abs043.svg";
// export { ReactComponent as ABS44 } from "./dualtone/abs044.svg";
// export { ReactComponent as ABS45 } from "./dualtone/abs045.svg";
export { ReactComponent as ABS46 } from "./dualtone/abs046.svg";
// export { ReactComponent as ABS47 } from "./dualtone/abs047.svg";
// export { ReactComponent as ABS48 } from "./dualtone/abs048.svg";
// export { ReactComponent as ABS49 } from "./dualtone/abs049.svg";
export { ReactComponent as ARR01 } from "./dualtone/arr001.svg";
export { ReactComponent as ARR02 } from "./dualtone/arr002.svg";
// export { ReactComponent as ARR03 } from "./dualtone/arr003.svg";
// export { ReactComponent as ARR04 } from "./dualtone/arr004.svg";
// export { ReactComponent as ARR05 } from "./dualtone/arr005.svg";
// export { ReactComponent as ARR06 } from "./dualtone/arr006.svg";
export { ReactComponent as ARR07 } from "./dualtone/arr007.svg";
// export { ReactComponent as ARR08 } from "./dualtone/arr008.svg";
export { ReactComponent as ARR09 } from "./dualtone/arr009.svg";
export { ReactComponent as ARR10 } from "./dualtone/arr010.svg";
// export { ReactComponent as ARR11 } from "./dualtone/arr011.svg";
export { ReactComponent as ARR12 } from "./dualtone/arr012.svg";
// export { ReactComponent as ARR13 } from "./dualtone/arr013.svg";
// export { ReactComponent as ARR14 } from "./dualtone/arr014.svg";
// export { ReactComponent as ARR15 } from "./dualtone/arr015.svg";
export { ReactComponent as ARR16 } from "./dualtone/arr016.svg";
// export { ReactComponent as ARR17 } from "./dualtone/arr017.svg";
// export { ReactComponent as ARR18 } from "./dualtone/arr018.svg";
// export { ReactComponent as ARR19 } from "./dualtone/arr019.svg";
export { ReactComponent as ARR20 } from "./dualtone/arr020.svg";
// export { ReactComponent as ARR21 } from "./dualtone/arr021.svg";
export { ReactComponent as ARR22 } from "./dualtone/arr022.svg";
// export { ReactComponent as ARR23 } from "./dualtone/arr023.svg";
export { ReactComponent as ARR24 } from "./dualtone/arr024.svg";
export { ReactComponent as ARR25 } from "./dualtone/arr025.svg";
// export { ReactComponent as ARR26 } from "./dualtone/arr026.svg";
// export { ReactComponent as ARR27 } from "./dualtone/arr027.svg";
export { ReactComponent as ARR28 } from "./dualtone/arr028.svg";
// export { ReactComponent as ARR29 } from "./dualtone/arr029.svg";
// export { ReactComponent as ARR30 } from "./dualtone/arr030.svg";
// export { ReactComponent as ARR31 } from "./dualtone/arr031.svg";
// export { ReactComponent as ARR32 } from "./dualtone/arr032.svg";
export { ReactComponent as ARR33 } from "./dualtone/arr033.svg";
// export { ReactComponent as ARR34 } from "./dualtone/arr034.svg";
// export { ReactComponent as ARR35 } from "./dualtone/arr035.svg";
export { ReactComponent as ARR36 } from "./dualtone/arr036.svg";
export { ReactComponent as ARR37 } from "./dualtone/arr037.svg";
// export { ReactComponent as ARR38 } from "./dualtone/arr038.svg";
// export { ReactComponent as ARR39 } from "./dualtone/arr039.svg";
// export { ReactComponent as ARR40 } from "./dualtone/arr040.svg";
// export { ReactComponent as ARR41 } from "./dualtone/arr041.svg";
export { ReactComponent as ARR42 } from "./dualtone/arr042.svg";
// export { ReactComponent as ARR43 } from "./dualtone/arr043.svg";
// export { ReactComponent as ARR44 } from "./dualtone/arr044.svg";
// export { ReactComponent as ARR45 } from "./dualtone/arr045.svg";
// export { ReactComponent as ARR46 } from "./dualtone/arr046.svg";
// export { ReactComponent as ARR47 } from "./dualtone/arr047.svg";
// export { ReactComponent as ARR48 } from "./dualtone/arr048.svg";
// export { ReactComponent as ARR49 } from "./dualtone/arr049.svg";
// export { ReactComponent as ARR50 } from "./dualtone/arr050.svg";
// export { ReactComponent as ARR51 } from "./dualtone/arr051.svg";
// export { ReactComponent as ARR52 } from "./dualtone/arr052.svg";
// export { ReactComponent as ARR53 } from "./dualtone/arr053.svg";
// export { ReactComponent as ARR54 } from "./dualtone/arr054.svg";
// export { ReactComponent as ARR55 } from "./dualtone/arr055.svg";
// export { ReactComponent as ARR56 } from "./dualtone/arr056.svg";
// export { ReactComponent as ARR57 } from "./dualtone/arr057.svg";
export { ReactComponent as ARR58 } from "./dualtone/arr058.svg";
export { ReactComponent as ARR59 } from "./dualtone/arr059.svg";
// export { ReactComponent as FIL01 } from "./dualtone/fil001.svg";
// export { ReactComponent as FIL02 } from "./dualtone/fil002.svg";
// export { ReactComponent as FIL03 } from "./dualtone/fil003.svg";
// export { ReactComponent as FIL04 } from "./dualtone/fil004.svg";
// export { ReactComponent as FIL05 } from "./dualtone/fil005.svg";
// export { ReactComponent as FIL06 } from "./dualtone/fil006.svg";
// export { ReactComponent as FIL07 } from "./dualtone/fil007.svg";
// export { ReactComponent as FIL08 } from "./dualtone/fil008.svg";
// export { ReactComponent as FIL09 } from "./dualtone/fil009.svg";
// export { ReactComponent as FIL10 } from "./dualtone/fil010.svg";
// export { ReactComponent as FIL11 } from "./dualtone/fil011.svg";
// export { ReactComponent as FIL12 } from "./dualtone/fil012.svg";
// export { ReactComponent as FIL13 } from "./dualtone/fil013.svg";
// export { ReactComponent as FIL14 } from "./dualtone/fil014.svg";
// export { ReactComponent as FIL15 } from "./dualtone/fil015.svg";
// export { ReactComponent as FIL16 } from "./dualtone/fil016.svg";
// export { ReactComponent as FIL17 } from "./dualtone/fil017.svg";
// export { ReactComponent as FIL18 } from "./dualtone/fil018.svg";
// export { ReactComponent as FIL19 } from "./dualtone/fil019.svg";
// export { ReactComponent as FIL20 } from "./dualtone/fil020.svg";
export { ReactComponent as FIL21 } from "./dualtone/fil021.svg";
// export { ReactComponent as FIL22 } from "./dualtone/fil022.svg";
// export { ReactComponent as FIL23 } from "./dualtone/fil023.svg";
// export { ReactComponent as GEN01 } from "./dualtone/gen001.svg";
export { ReactComponent as GEN02 } from "./dualtone/gen002.svg";
export { ReactComponent as GEN03 } from "./dualtone/gen003.svg";
export { ReactComponent as GEN04 } from "./dualtone/gen004.svg";
// export { ReactComponent as GEN05 } from "./dualtone/gen005.svg";
// export { ReactComponent as GEN06 } from "./dualtone/gen006.svg";
// export { ReactComponent as GEN07 } from "./dualtone/gen007.svg";
// export { ReactComponent as GEN08 } from "./dualtone/gen008.svg";
// export { ReactComponent as GEN09 } from "./dualtone/gen009.svg";
// export { ReactComponent as GEN10 } from "./dualtone/gen010.svg";
export { ReactComponent as GEN11 } from "./dualtone/gen011.svg";
// export { ReactComponent as GEN12 } from "./dualtone/gen012.svg";
export { ReactComponent as GEN13 } from "./dualtone/gen013.svg";
// export { ReactComponent as GEN14 } from "./dualtone/gen014.svg";
export { ReactComponent as GEN15 } from "./dualtone/gen015.svg";
export { ReactComponent as GEN16 } from "./dualtone/gen016.svg";
export { ReactComponent as GEN17 } from "./dualtone/gen017.svg";
// export { ReactComponent as GEN18 } from "./dualtone/gen018.svg";
export { ReactComponent as GEN19 } from "./dualtone/gen019.svg";
export { ReactComponent as GEN20 } from "./dualtone/gen020.svg";
// export { ReactComponent as GRA01 } from "./dualtone/gra001.svg";
// export { ReactComponent as GRA02 } from "./dualtone/gra002.svg";
// export { ReactComponent as GRA03 } from "./dualtone/gra003.svg";
export { ReactComponent as GRA04 } from "./dualtone/gra004.svg";
// export { ReactComponent as GRA05 } from "./dualtone/gra005.svg";
export { ReactComponent as GRA06 } from "./dualtone/gra006.svg";
// export { ReactComponent as GRA07 } from "./dualtone/gra007.svg";
// export { ReactComponent as GRA08 } from "./dualtone/gra008.svg";
export { ReactComponent as GRA09 } from "./dualtone/gra009.svg";
export { ReactComponent as GRA10 } from "./dualtone/gra010.svg";
export { ReactComponent as GRA11 } from "./dualtone/gra011.svg";
export { ReactComponent as GRA12 } from "./dualtone/gra012.svg";
export { ReactComponent as Trophy } from "./dualtone/Trophy.svg";

export { ReactComponent as Discord } from "./discord.svg";
export { ReactComponent as TG } from "./tg.svg";
export { ReactComponent as TW } from "./tw.svg";

export { ReactComponent as Tonviewer } from "./tonviewer.svg";
export { ReactComponent as Tonscan } from "./tonscan.svg";

export { ReactComponent as Payment } from "./material/payment.svg";
export { ReactComponent as Link } from "./material/link.svg";
export { ReactComponent as Arrowright } from "./material/arrowRight.svg";
export { ReactComponent as Android } from "./material/android.svg";
export { ReactComponent as Announcement } from "./material/announcement.svg";
export { ReactComponent as Copy } from "./material/copy.svg";

export { ReactComponent as Arrowtechart } from "./arrowtechart.svg";
export { ReactComponent as Ton } from "./ton.svg";
export { ReactComponent as TransparentTon } from "./transparentton.svg";

export { ReactComponent as Explore } from "./explore.svg";
export { ReactComponent as Code } from "./code.svg";
export { ReactComponent as Tools } from "./tools.svg";
export { ReactComponent as Trust } from "./trust.svg";
export { ReactComponent as Diamond } from "./diamond.svg";
export { ReactComponent as Info } from "./info.svg";
export { ReactComponent as Heart } from "./heart.svg";
export { ReactComponent as Gmail } from "./gmail.svg";
export { ReactComponent as Web } from "./web.svg";
