import { useTranslation } from "react-i18next";
import { Grid, Spacer, Container, Text } from "@nextui-org/react";

export function Privacy() {
  const { t } = useTranslation();

  return (
    <>
      <Container md css={{ p: 0 }}>
        <Grid.Container
          gap={1}
          justify="center"
          css={{ minHeight: "70vh", pt: 16, pb: 32, pl: 0, pr: 0 }}
        >
          <Grid xs={12} sm={8}>
            <Grid.Container
              gap={1}
              justify="space-between"
              css={{ m: "-$8", width: "calc(100% + $16)" }}
            >
              <Grid xs={12} className="flex flex-col">
                <Text weight="bold" size={24}>
                  Privacy Policy
                </Text>
                <br />
                <Text>
                  At FCK.Foundation, we are committed to safeguarding the
                  privacy of our website visitors. This Privacy Policy outlines
                  the types of information we collect and how we use it. By
                  using our website, you consent to the practices described
                  below.
                </Text>

                <br />
                <Text weight="bold" size={16}>
                  Collection and Use of Cookies:
                </Text>
                <Text>
                  We may use cookies and similar tracking technologies to
                  enhance your browsing experience on our website. Cookies are
                  small text files that are placed on your computer or device
                  when you visit certain web pages. These files allow us to
                  remember your preferences and provide you with a more
                  personalized experience.
                </Text>

                <br />
                <Text weight="bold" size={16}>
                  Google Analytics:
                </Text>
                <Text>
                  We utilize Google Analytics, a web analytics service provided
                  by Google, Inc. ("Google"). Google Analytics uses cookies to
                  help us analyze how users interact with our website. The
                  information generated by these cookies (including your IP
                  address) will be transmitted to and stored by Google on
                  servers in the United States. This data is used for the sole
                  purpose of evaluating website traffic, trends, and gathering
                  other valuable information to help us improve our services.
                </Text>

                <br />
                <Text weight="bold" size={16}>
                  Data Storage and User Information:
                </Text>
                <Text>
                  We want to clarify that we do not store any personal
                  information of our website visitors. We exclusively rely on
                  open data collected from the blockchain. Any data we collect
                  or process is limited to public blockchain data only, ensuring
                  user anonymity and privacy.
                </Text>

                <br />
                <Text weight="bold" size={16}>
                  Third-Party Websites:
                </Text>
                <Text>
                  Our website may contain links to third-party websites. Please
                  be aware that we are not responsible for the privacy practices
                  or content of these third-party sites. We encourage you to
                  read the privacy policies of any website you visit from our
                  platform.
                </Text>

                <br />
                <Text weight="bold" size={16}>
                  Changes to this Privacy Policy:
                </Text>
                <Text>
                  We reserve the right to update or modify this Privacy Policy
                  at any time. Any changes will be posted on this page, and the
                  revised date at the bottom will be updated accordingly. We
                  encourage you to review this Privacy Policy regularly for any
                  updates.
                </Text>

                <br />
                <Text className="flex">
                  If you have any questions or concerns regarding these Terms,
                  please contact us at <Spacer x={0.4} />
                  <a href="mailto:support@fck.foundation" target="__blank">
                    support@fck.foundation
                  </a>
                  .
                </Text>

                <br />
                <div className="flex">
                  <Text weight="bold" size={14}>
                    Last updated:
                  </Text>{" "}
                  <Spacer x={0.4} /> <Text>03.07.2023</Text>
                </div>
              </Grid>
            </Grid.Container>
          </Grid>
        </Grid.Container>
      </Container>
      <Spacer y={0.4} />
    </>
  );
}
